@startuml monitoring

skinparam linetype ortho
skinparam monochrome false
skinparam componentStyle uml2
skinparam backgroundColor #fff
skinparam ArrowColor black
skinparam NoteBorderColor Grey
skinparam NoteBackgroundColor #fdfdfd
skinparam defaultTextAlignment center
skinparam activity {
FontName Ubuntu
}

rectangle monitoring as "monitoring.fritz.box" <<RasPi>> {
  component grafana
  component prometheus
  prometheus -> grafana
}

rectangle supervisor as "supervisor.fritz.box" <<RasPi>> {
  component tmp_grafana as "grafana"
  component tmp_prometheus as "prometheus"
  tmp_prometheus -> tmp_grafana
}
note right of supervisor: Temporary stack to check if the actual\nmonitoring stack in prometheus.fritz.box is stable\nand the RasPi node provides enough resources.

rectangle clients <<multiple>> {
  component node_exporter
  component cAdvisor
}
note bottom of clients: kobol.fritz.box\ncaprica.fritz.box\nall RasPi nodes

clients -left-> monitoring
monitoring -down-> supervisor

@enduml
