= Workstation `caprica`
Sebastian Sommerfeld <sebastian@sommerfeld.io>

== Install Ubuntu from bootable USB stick
. Download Ubuntu from the link:https://ubuntu.com[Ubuntu website].
. Create a bootable USB stick from the downloaded iso image with a tool like link:https://www.balena.io/etcher[Etcher] or the Startup Disk Creator (shipped with Ubuntu).
. Install machine from stick (the setup wizard takes care of the hostname, network settings, ssh, ...)
.. When prompted for a user and password, use the same information as in kobol.
.. Remember to install and activate the OpenSSH server when the wizard prompts for this!
.. Do not install any futher software packages. Installations take place later on when provisioning the system using Ansible.
. Test connecting to `caprica` via `ssh sebastian@caprica.fritz.box` (with sebastian being the user created while installing the OS).

== Risks and Technical Debts
Scale for Probability and Impact: Low, Medium and High

[cols="1,3,5,1,1,1", options="header"]
|===
|# |Title |Description |Probability |Impact |Response
|{counter:usage} |none |none |none |none |none ||none
|===
