= Github Configuration

The basic configuration for all (relevant) link:https://github.com/sebastian-sommerfeld-io?tab=repositories[Github Repositories] is done from a Github Actions workflow to ensure all repositories are set up in a similar way and to avoid manual steps as much as possible. Additionally the config is updated to the desired state regularly to avoid (invalid) updates (which mostly are done manually). Terraform is used to ensure this desired consistent state accross all repositories.

* The Github Actions workflow: link:https://github.com/sebastian-sommerfeld-io/configs/actions/workflows/configure-github.yml[Apply global Github config ]

== Prerequisites
. link:https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token[Create a Personal Access Token] for your Github Account to use with Terraform. The minimum required scopes are `repo` and `read:user`
. Create Actions secrets for link:https://github.com/sebastian-sommerfeld-io/configs[sebastian-sommerfeld-io/configs] repo
.. `BW_CLIENT_ID`: _https://vault.bitwarden.com -> Account Settings -> Security -> View API key_
.. `BW_CLIENT_SECRET`: _https://vault.bitwarden.com -> Account Settings -> Security -> View API key_
.. `BW_MASTER_PASS`: _https://vault.bitwarden.com -> Account Settings -> Security -> View API key_
.. `TERRAFORM`: The Github Personal Access Token _link:https://github.com/settings/tokens[github.com/settings/tokens -> Settings Developer settings -> Tokens (classic)]_

== Building Blocks
The Github Actions workflow configures issue labels and secrets for a lot of Github repositories. It needs four Actions secrets configured (see Prerequisites) to access Bitwarden (`BW_*` -> load other secrets) and to access Github repositories and projects (`TERRAFORM`).

[plantuml, puml-build-image, svg]
----
@startuml

skinparam linetype ortho
skinparam monochrome false
skinparam componentStyle uml2
skinparam backgroundColor transparent
skinparam ArrowColor black
skinparam ComponentBackgroundColor #fdfdfd
skinparam CollectionsBackgroundColor #ffffff
skinparam NoteBorderColor Grey
skinparam NoteBackgroundColor #fdfdfd
skinparam defaultTextAlignment center
skinparam activity {
FontName Ubuntu
}

component configs <<Github Repo>> {
  queue wf as "Global: Apply Github Configuration" <<Github Actions Workflow>>
  collections s1 as "BW_CLIENT_ID\nBW_CLIENT_SECRET\nBW_MASTER_PASS\nTERRAFORM" <<Actions Secrets>>
  
  s1 -right-> wf
}

component bitwarden <<Secrets Provider>> {
  collections s2 as "Repo-specific secrets"
}

s2 -down-> wf

component repo_1 <<Github Repo>>
component repo_2 <<Github Repo>>
component repo_x as "repo_..." <<Github Repo>>
component repo_n <<Github Repo>>

wf -down-> repo_1
wf -down-> repo_2
wf -down-> repo_x
wf -down-> repo_n

component tf_state as "<b>configs-persistent-data</b>\nterraform state" <<Github Repo>>
wf -> tf_state
tf_state -> wf

@enduml
----

The Terraform state is stored in a separate private repository. The pipeline clones this repo, applies the Terraform config and pushes the updated Terraform state back to the repository.

== Terraform Config
=== Available (Terraform) commands
The `xref:AUTO-GENERATED:bash-docs/src/main/github/apply-config-sh.adoc[apply-config.sh]` script can handle these commands. Wile developing use `xref:AUTO-GENERATED:bash-docs/src/main/github/run-local-sh.adoc[run-local.sh]` on your localhost instead of direct calls to this script. `run-local.sh` provides a more conviniert
way to trigger the terraform commands.

include::ROOT:partial$GENERATED/github/config/help.adoc[]

// === Generated Terraform docs
include::ROOT:partial$GENERATED/github/config/terraform-docs.adoc[]
