# -*- mode: ruby -*-
# vi: set ft=ruby :

IMAGE_NAME = "ubuntu/jammy64" # = 22.04

ANSIBLE_GROUP="raspi"
NODE_NAME="#{ANSIBLE_GROUP}-"
NODE_COUNT = 3 # number of nodes

Vagrant.configure("2") do |config|
    (1..NODE_COUNT).each do |i|
        config.vm.define "#{NODE_NAME}#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.56.#{i + 10}"
            node.vm.hostname = "#{NODE_NAME}#{i}"

            node.vm.provider "virtualbox" do |v|
                v.memory = 2048
                v.cpus = 1
                v.name = "#{NODE_NAME}#{i}"
            end
            
            node.vm.provision :ansible do |ansible|
                ansible.playbook = "../../../ansible/playbooks/raspi.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.50.#{10 + i}",
                    ansible_user: "vagrant",
                    ps1: '${debian_chroot:+($debian_chroot)}\[\033[01;36m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(__git_ps1) $ ',
                }
                ansible.groups = {
                  "#{ANSIBLE_GROUP}" => ["#{NODE_NAME}#{i}"]
                }
            end

            node.vm.network "forwarded_port", guest: 8000, host: "#{8000 + i}"
        end
    end
end
